### ISSUE TITLE
conda install the wrong version of pinocchio when tsid is installed

### ISSUE THREAD

**Issue by GiulioRomualdi** [conda-forge/tsid-feedstock#3]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Hi all, 

I tried to install `tsid` in a clean conda environment with the following command
```
conda install -c conda-forge tsid
```
If I tried to load `tsid` from python I got the following error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gromualdi/mambaforge/envs/tsid-env/lib/python3.9/site-packages/tsid/__init__.py", line 1, in <module>
    from .libtsid_pywrap import *
ImportError: libpinocchio.so.2.6.0: cannot open shared object file: No such file or directory
```

This error is actually expected since the automatically installed `pinocchio` version by `conda` is `2.6.3`.

A workaround is to force the Pinocchio version to `2.6.0` with
```
conda install -c conda-forge tsid pinocchio=2.6.0
```

<br/>
Environment (<code>conda list</code>):
<details>

```
conda list
# packages in environment at /home/gromualdi/mambaforge/envs/tsid-env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
assimp                    5.0.1                hedfc422_6    conda-forge
boost                     1.74.0           py39h5472131_3    conda-forge
boost-cpp                 1.74.0               h312852a_4    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
console_bridge            1.0.1                h4bd325d_0    conda-forge
eigen                     3.4.0                h4bd325d_0    conda-forge
eigenpy                   2.6.8           py39h5aed9d1_10    conda-forge
eiquadprog                1.2.3                h8cbb357_0    conda-forge
hpp-fcl                   1.7.7            py39hbcdfc36_2    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libblas                   3.9.0           11_linux64_openblas    conda-forge
libcblas                  3.9.0           11_linux64_openblas    conda-forge
libffi                    3.4.2                h9c3ff4c_4    conda-forge
libgcc-ng                 11.2.0              h1d223b6_10    conda-forge
libgfortran-ng            11.2.0              h69a702a_10    conda-forge
libgfortran5              11.2.0              h5c6108e_10    conda-forge
liblapack                 3.9.0           11_linux64_openblas    conda-forge
libopenblas               0.3.17          pthreads_h8fe5266_1    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_10    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
llvm-openmp               12.0.1               h4bd325d_1    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
numpy                     1.21.2           py39hdbf815f_0    conda-forge
octomap                   1.9.7                h4bd325d_0    conda-forge
openssl                   3.0.0                h7f98852_1    conda-forge
pinocchio                 2.6.3            py39hbcdfc36_2    conda-forge
pip                       21.3               pyhd8ed1ab_0    conda-forge
python                    3.9.7           hf930737_3_cpython    conda-forge
python_abi                3.9                      2_cp39    conda-forge
qhull                     2020.2               h4bd325d_2    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
setuptools                58.2.0           py39hf3d152e_0    conda-forge
sqlite                    3.36.0               h9cd32fc_2    conda-forge
tinyxml                   2.6.2                h4bd325d_2    conda-forge
tk                        8.6.11               h27826a3_1    conda-forge
tsid                      1.6.0            py39hbcdfc36_0    conda-forge
tzdata                    2021c                he74cb21_0    conda-forge
urdfdom                   2.3.5                h4bd325d_0    conda-forge
urdfdom_headers           1.0.5                h4bd325d_2    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.0                ha95c52a_0    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
     active environment : tsid-env
    active env location : /home/gromualdi/mambaforge/envs/tsid-env
            shell level : 1
       user config file : /home/gromualdi/.condarc
 populated config files : /home/gromualdi/mambaforge/.condarc
                          /home/gromualdi/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.6.final.0
       virtual packages : __linux=5.11.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/gromualdi/mambaforge  (writable)
      conda av data dir : /home/gromualdi/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/gromualdi/mambaforge/pkgs
                          /home/gromualdi/.conda/pkgs
       envs directories : /home/gromualdi/mambaforge/envs
                          /home/gromualdi/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.6 Linux/5.11.0-37-generic ubuntu/20.04.3 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</details>

**Comment by jcarpent** [comment]
Sorry for the delay!
I will fix it ;)
Thanks

**Comment by GiulioRomualdi** [comment]
Thank you @jcarpent !!
